apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: q0bfhp79s-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/q0bfhp79s-dotnet-basic-gitops